# Generated by Django 4.0.4 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Cooking', 'Cooking'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
