# Generated by Django 4.0.4 on 2022-05-30 21:29

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('plate_size', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=menu.models.generate_img_file_path)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
